// Generated by scripts/generate-index.mjs. DO NOT EDIT BY HAND.
export type AvatarEntry = {
  batch: string;
  filename: string;
  path: string;
  stem: string;
  title: string;
  tokens: readonly string[];
  timestamp?: string;
  url: string;
};

export const avatars: readonly AvatarEntry[];

