// Generated by scripts/generate-index.mjs. DO NOT EDIT BY HAND.
const path = require('node:path');
const { pathToFileURL } = require('node:url');

module.exports = pathToFileURL(path.join(__dirname, "../Sheep_Paper_Working.svg")).href;
